### ISSUE TITLE
Everything broke except for the graphs after commit 7a73de3efb8f6dcd3a134f0688b2c4f7fa3d8e62

### ISSUE THREAD

**Issue by m-rtijn** [FredrikAugust/server-status#7]
CTRL+SHIFT+J gives: Uncaught TypeError: Cannot read property '1' of null main.js:35

**Comment by FredrikAugust** [comment]
Is this fixed in latest commit?

**Comment by m-rtijn** [comment]
Yes! Everything works again now. Thanks!

**Comment by FredrikAugust** [comment]
You are welcome. :dancer:
